// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcJrfgH0-BZeFowDBnt1FZ63-X5EZmMRM',
    appId: '1:894671466219:web:e5e847757d67875eb898ae',
    messagingSenderId: '894671466219',
    projectId: 'todo-app-19eba',
    authDomain: 'todo-app-19eba.firebaseapp.com',
    storageBucket: 'todo-app-19eba.appspot.com',
    measurementId: 'G-GN0VJHEK62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoCeig-ZqdaH4W03MJF5ZvVbnLYX4tF1s',
    appId: '1:894671466219:android:82bb08cb69fd57c5b898ae',
    messagingSenderId: '894671466219',
    projectId: 'todo-app-19eba',
    storageBucket: 'todo-app-19eba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYnGUdjhF36xYwMLhJRvDw-NQhg9PkO54',
    appId: '1:894671466219:ios:540b366884d15805b898ae',
    messagingSenderId: '894671466219',
    projectId: 'todo-app-19eba',
    storageBucket: 'todo-app-19eba.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYnGUdjhF36xYwMLhJRvDw-NQhg9PkO54',
    appId: '1:894671466219:ios:1a9faaf0d499c9d3b898ae',
    messagingSenderId: '894671466219',
    projectId: 'todo-app-19eba',
    storageBucket: 'todo-app-19eba.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
